version: '3.8'

services:
  app:
    image: spring-petclinic:latest
    container_name: spring-petclinic-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      SPRING_PROFILES_ACTIVE: postgres
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
      POSTGRES_DB: petclinic
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data  # Volume for PostgreSQL data persistence
    networks:
      - app-network

networks:
  app-network:
    name: app-network

volumes:
  db-data:
    name: db-data
