receivers:
  otlp:
    protocols:
      grpc:
      http:

extensions:
  basicauth/client:
    client_auth: 
      username: 738734
      password: glc_eyJvIjoiOTQzMDk3IiwibiI6Im90bHAtb3RscCIsImsiOiJEWnhpNTFsZVZWMHJYcTg5MTVqODJOOEgiLCJtIjp7InIiOiJ1cyJ9fQ==

exporters:
  otlp/jaeger:
    endpoint: "jaeger:4320"
    tls:
      insecure: true
  otlphttp/grafana:
    endpoint: https://otlp-gateway-prod-us-east-0.grafana.net/otlp
    auth:
      authenticator: basicauth/client
    tls:
      insecure: false

  otlp/digma:
    endpoint: ${OTLP_EXPORTER_DIGMA_COLLECTOR_API}
    tls:
      insecure: true

processors:
  batch:

service:
  extensions: [basicauth/client]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/grafana,otlp/digma,otlp/jaeger]
      processors: [batch]