version: "3.6"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    volumes:
      - badger_data:/badger
    ports:
      - "16686:16686"
      - "14250"
      - "0.0.0.0:14268:14268"
    environment:
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_SPAN_STORE_TTL=2000h
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key

  collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/otel-local-config.yaml"]
    volumes:
      - ./collector-config.yaml:/otel-local-config.yaml
    ports:
      - "0.0.0.0:4318:4318" # HTTP OTLP receiver
      - "0.0.0.0:8889:8889" # METRICS
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - jaeger
    environment:
      - OTLP_EXPORTER_DIGMA_COLLECTOR_API=host.docker.internal:5050

networks:
  default:
    name: tracing-network

volumes:
  badger_data:
