version: "3.6"

services:
  
  collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/otel-local-config.yaml"]
    volumes:
      - ./collector-config.yaml:/otel-local-config.yaml
    ports:
      - "0.0.0.0:4317:4317" # OTLP receiver
      - "0.0.0.0:8889:8889" # METRICS
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OTLP_EXPORTER_DIGMA_COLLECTOR_API=host.docker.internal:5050

networks:
  default:
    name: tracing-network

volumes:
  badger_data: