name: CI Pipeline

on:
  push:
    branches:
     - main
     - deploy-automation
  pull_request:
     - main
     - deploy-automation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4 
      with:
        name: build-artifacts
        path: target/**

    - name: Run Unit Tests
      run: mvn test

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4 
      with:
        name: test-reports
        path: target/surefire-reports/**

    - name: Generate Code Coverage Report
      run: mvn jacoco:report

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v4 
      with:
        name: code-coverage-report
        path: target/site/jacoco/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t samanthayeep/petclinic-app:latest .

      - name: Push Docker Image
        run: docker push samanthayeep/petclinic-app:latest

      - name: Deploy Docker Container
        run: docker run -d -p 8082:8082 samanthayeep/petclinic-app:latest
