---
    name: Build to Docker Hub
    
    on:
      push:
        branches: [main]
    
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the repository
            uses: actions/checkout@v4
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Login to Jfrog Artifactory
            uses: docker/login-action@v3
            with:
              registry: rodi26.jfrog.io
              username: 'rodolphe.fontaine@orange.fr'
              password: ${{ secrets.JF_ACCESS_TOKEN }}
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              push: true
              tags: rodi26.jfrog.io/spring-petclinic:latest