# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
      - name: Instrument app
        uses: digma-ai/digma-java-instrumentation-action@v1.0.2
        with:
          # Assuming the action expects these inputs:
          collector_url: 'http://example.com/collector'
          service_name: 'spring-petclinic'
          environment: 'PETCLINIC_CI'

      - name: Build with Maven Wrapper
        run: mvn '-Dtest=org.springframework.samples.petclinic.integration.*Tests' test
