name: 'vulnerability-scan'

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          # exit-code: '1'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
      
      - name: create issue in github
        uses: knqyf263/trivy-issue-action@v0.0.6
        with:
          # Label name
          # Default: vulnerability (this label must be created in advance)
          label: 'vulnerability'

          # Severities of vulnerabilities to be registered to GitHub Issues
          # Default: 'CRITICAL'
          severity: 'CRITICAL,HIGH'
          
          # Comma separated list of directories where traversal is skipped
          # Default: ''
          # Example: 'tests, integration-tests'
          skip-dirs: ''

          # Assignees
          # Default: ''
          # Example: 'monalisa,hubot'
          assignee: ''

          # Project ID to which the created Issue will be tied.
          # Default: ''
          project-id: ''
