name: Test Action
on:
  push
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: src/test/jmeter/petclinic_test_plan.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO" 